name: Deploy your branch to dev
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy on which enviroment'
        type: choice
        required: true
        default: dev
        options:
          - dev
          - dev1
          - dev2
          - dev3
          - dev4
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: ./.github

env:
  AWS_REGION: us-east-1
  ENV: ${{ github.events.inputs.enviroment}}
  # LAMBDA_FUNCTION_NAME: ${{ env.ENV == 'dev' && 'dev-consent-backend' || env.ENV == 'dev1' && 'dev1-consent-backend' || env.ENV == 'dev2' && 'copilot-dev2-consent-backend' || env.ENV == 'dev3' && 'copilot-dev3-consent-backend' || env.ENV == 'dev4' && 'copilot-dev4-consent-backend' }}
  LAMBDA_FUNCTION_NAME : "dev-consent-backend"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump github events and other vars
        run: echo '${{ toJSON(github.event.inputs) }}' && echo '${{ toJSON(github.ref_name) }}' && echo '${{ toJSON(github.head_ref) }}'
      - name: Display workflow file
        run: cat workflows/deploy_to_dev.yml
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #   #   aws-access-key-id: ASIAU2SYT7GJTG7DO2NO
      #   #   aws-secret-access-key: egNYENtHQ9IlT5y2GNwMjpDy7jnmlxdwcpyVCHyN
      #     aws-region: ${{ env.AWS_REGION }}
      - name: Check AWS version
        run: |
          aws --version
          x='avinash'

      # - name: Zip Lambda Function
      #   run: zip -r updated_lambda_function.zip node/dev-consent-backend/*
      - name: Get Lambda function name
        run: |
          echo $x
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "LAMBDA_FUNCTION_NAME=dev-consent-backend" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "dev1" ]]; then
            echo "LAMBDA_FUNCTION_NAME=dev1-consent-backend" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "dev2" ]]; then
            echo "LAMBDA_FUNCTION_NAME=copilot-dev2-consent-backend" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "dev3" ]]; then
            echo "LAMBDA_FUNCTION_NAME=copilot-dev3-consent-backend" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "dev4" ]]; then
            echo "LAMBDA_FUNCTION_NAME=copilot-dev4-consent-backend" >> $GITHUB_ENV
          else
            echo "Unknown Environment"
            exit 1
          fi
      - name: Deploy to Lambda
        # run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://updated_lambda_function.zip
        run: echo $LAMBDA_FUNCTION_NAME 123
