name: Deploy your branch to dev
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy on which enviroment'
        type: choice
        required: true
        default: dev
        options:
          - dev
          - dev1
          - dev2
          - dev3
          - dev4
        
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump github events and other vars
        run: echo '${{ toJSON(github.event.inputs) }}' && echo '${{ toJSON(github.ref_name) }}' && echo '${{ toJSON(github.head_ref) }}'
        shell: bash
      - name: Display workflow file
        run: cat .github/worflows/deploy_to_dev.yml
