name: Deploy your branch to dev
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy on which enviroment'
        type: choice
        required: true
        default: dev
        options:
          - dev
          - dev1
          - dev2
          - dev3
          - dev4
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: ./.github
env:
  AWS_REGION: us-east-1     
        
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump github events and other vars
        run: echo '${{ toJSON(github.event.inputs) }}' && echo '${{ toJSON(github.ref_name) }}' && echo '${{ toJSON(github.head_ref) }}'
      - name: Display workflow file
        run: cat workflows/deploy_to_dev.yml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        # with:
        #   aws-access-key-id: ASIAU2SYT7GJTG7DO2NO
        #   aws-secret-access-key: egNYENtHQ9IlT5y2GNwMjpDy7jnmlxdwcpyVCHyN
          aws-region: ${{ env.AWS_REGION }}
      - name: Check AWS version
        run: aws --version
